/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RecordRegistry } from "./RecordRegistry";
export * as factories from "./factories";
export { RecordRegistry__factory } from "./factories/RecordRegistry__factory";
