/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace RecordRegistry {
  export type AnchorStruct = {
    recordHash: BytesLike;
    verifier: AddressLike;
    timestamp: BigNumberish;
  };

  export type AnchorStructOutput = [
    recordHash: string,
    verifier: string,
    timestamp: bigint
  ] & { recordHash: string; verifier: string; timestamp: bigint };
}

export interface RecordRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorRecord"
      | "getAnchorCount"
      | "getHistory"
      | "getLatestAnchor"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RecordAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorRecord",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getHistory", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getLatestAnchor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestAnchor",
    data: BytesLike
  ): Result;
}

export namespace RecordAnchoredEvent {
  export type InputTuple = [
    recordId: string,
    hash: BytesLike,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    hash: string,
    verifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    hash: string;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RecordRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RecordRegistry;
  waitForDeployment(): Promise<this>;

  interface: RecordRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorRecord: TypedContractMethod<
    [recordId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  getAnchorCount: TypedContractMethod<[recordId: string], [bigint], "view">;

  getHistory: TypedContractMethod<
    [recordId: string],
    [RecordRegistry.AnchorStructOutput[]],
    "view"
  >;

  getLatestAnchor: TypedContractMethod<
    [recordId: string],
    [
      [string, string, bigint] & {
        recordHash: string;
        verifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorRecord"
  ): TypedContractMethod<
    [recordId: string, hash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAnchorCount"
  ): TypedContractMethod<[recordId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [recordId: string],
    [RecordRegistry.AnchorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestAnchor"
  ): TypedContractMethod<
    [recordId: string],
    [
      [string, string, bigint] & {
        recordHash: string;
        verifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RecordAnchored"
  ): TypedContractEvent<
    RecordAnchoredEvent.InputTuple,
    RecordAnchoredEvent.OutputTuple,
    RecordAnchoredEvent.OutputObject
  >;

  filters: {
    "RecordAnchored(string,bytes32,address,uint256)": TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
    RecordAnchored: TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
  };
}
